CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255),
    tipo VARCHAR(255)
);

CREATE TABLE simulado (
    id_simulado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255)
);

CREATE TABLE questao (
    id_questao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado VARCHAR(255),
    id_simulado BIGINT,
    CONSTRAINT fk_questao_simulado FOREIGN KEY (id_simulado) REFERENCES simulado(id_simulado)
);

CREATE TABLE resultado (
    id_resultado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pontuacao DOUBLE PRECISION,
    acertos INTEGER,
    total_questoes INTEGER,
    realizado_em TIMESTAMP,
    status VARCHAR(255),
    id_usuario BIGINT,
    id_simulado BIGINT,
    CONSTRAINT fk_resultado_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_resultado_simulado FOREIGN KEY (id_simulado) REFERENCES simulado(id_simulado)
);

CREATE TABLE resposta (
    id_resposta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alternativa_escolhida VARCHAR(255),
    id_resultado BIGINT,
    id_questao BIGINT,
    CONSTRAINT fk_resposta_resultado FOREIGN KEY (id_resultado) REFERENCES resultado(id_resultado),
    CONSTRAINT fk_resposta_questao FOREIGN KEY (id_questao) REFERENCES questao(id_questao)
);